name: Github CI pipeline teting the html file
on:
  push:
    branches:
      - main

    jobs:
        validate:
         run-on: ubuntu-latest
         steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Validate HTML file
    run: |
        if [-f "index.html"]; 
          then echo "index.html file exits".
        else
          echo "index.html fie does not exist"
        exit 1


